### ISSUE TITLE
Scrollback?

### ISSUE THREAD

**Issue by jgarte** [ninewise/st#1]
Hi,

I'm curious to know what your workflow is for getting scrollback functionality to see full output of commands.

Do you use `tee` or something else primarily?

**Comment by ninewise** [comment]
Usually I pipe to `less`. When I know I'll be doing a lot of interactive commands with longer output, I open a [`dvtm`](https://www.brain-dump.org/projects/dvtm/) session.

**Comment by jgarte** [comment]
> Usually I pipe to `less`. When I know I'll be doing a lot of interactive commands with longer output, I open a [`dvtm`](https://www.brain-dump.org/projects/dvtm/) session.

Thanks for sharing that.

Cool, I'll try that workflow out. Makes sense :)
